services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iqvia_python
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./reports:/app/reports
    ports:
      - "${PYTHON_PORT}:8888"
    depends_on:
      - postgres

volumes:
  postgres_data:
